config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "orders#index"

  resources :orders, only: [:index, :show] do
    collection do
      post 'parse_oc'
    end
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order

  validates :line_number, :item_number, :description, presence: true
  validates :quantity, :unit_price, presence: true
  validates :line_number, numericality: { greater_than: 0, only_integer: true },
    uniqueness: {scope: :order_id, message: 'line number is already in use'}
  validates :item_number, uniqueness: {scope: :order_id, message: 'item number is already in use'}
  validates :quantity, numericality: { greater_than: 0, only_integer: true }
  validates :unit_price, numericality: { greater_than: 0 }
end

app/models/order.rb
class Order < ActiveRecord::Base
  enum status: {
    pending:    'pending',
    processing: 'processing',
    success: 'success',
    rejected: 'rejected'
  }

  has_many :line_items, dependent: :destroy

  validates :confirmed_on, :vendor_name, :order_number, :status, presence: true
  validates :po_number, :total, presence: true
  validates :total, numericality: { greater_than: 0 }
  validates :order_number, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    order = Order.find params[:id]

    render json: { data: OrderSerializer.new(order).build_schema }
  end

  def parse_oc
    tempfile = params[:order][:order_confirmation_pdf].tempfile.path

    type, message = ParseOc.new(tempfile).perform!

    flash[type] = message

    redirect_to root_path, type => message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OrderConfirmations
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %br
    .container
      .row 
        - flash.each do |key, value|
          %div{class: "alert alert-#{key}"}= value
      .row
        = yield

app/views/orders/_order_details.html.haml
test

app/views/orders/index.html.haml
= simple_form_for :order, url: parse_oc_orders_path, html: { method: :post, multipart: true, class: 'form-inline' } do |f|
  = f.error_notification
 
  = f.input_field :order_confirmation_pdf, as: :file  

  .form-actions
    = f.button :submit, class: 'btn btn-success', value: 'Go'

%br
%br
%br
%table.table.table-bordered.table-hover
  %thead
    %tr 
      %th Confirmed on 
      %th Order number
      %th Vendor name
      %th Status
      %th PO Number 
      %th Total

  %tbody 
    - @orders.each do |order| 
      %tr
        %td= order.confirmed_on 
        %td= link_to order.order_number, order_path(order, format: :json)
        %td= order.vendor_name
        %td= order.status
        %td= order.po_number
        %td= order.total